# NumPy
NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

### Learning Objectives
***
* Understand the difference between one-, two- and n-dimensional arrays in NumPy;
* Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;
* Understand axis and shape properties for n-dimensional arrays.


## The Basics
***
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

NumPy’s array class is called ndarray. It is also known by the alias array. The more important attributes of ndarray are:

* ***ndarray.ndim*** : the number of axes (dimensions) of the array.
* ***ndarray.shape*** : the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.
* ***ndarray.size*** : the total number of elements of the array.
* ***ndarray.dtype*** : an object describing the type of the elements in the array. 
* ***ndarray.itemsize*** : the size in bytes of each element of the array.

In [2]:
import numpy as np

a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

### Creating arrays

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([(1.5, 2, 3), (4, 5, 6)])
c = np.array([[1, 2], [3, 4]], dtype=float)
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Adding, removing and sorting elements

In [28]:
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
b = np.array([1,2,3,4])
np.concatenate((a, b))

array([2, 1, 5, 3, 7, 4, 6, 8, 1, 2, 3, 4])

In [30]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

### Printing Arrays
Similar to nested lists, but with the following layout:
* the last axis is printed from left to right,
* the second-to-last is printed from top to bottom,
* the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [9]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [10]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Basic Operators

In [13]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a-b
c

array([20, 29, 38, 47])

In [14]:
b**2

array([0, 1, 4, 9])

In [15]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator

In [17]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [18]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [19]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b.sum(axis=0)   # sum of each column

array([12, 15, 18, 21])

In [21]:
b.min(axis=1)   # min of each row

array([0, 4, 8])

In [22]:
b.cumsum(axis=1)    # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.
***
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where
***

In [23]:
B = np.arange(3)
B

array([0, 1, 2])

In [24]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [25]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [31]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

### Copies and Views
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. There are 3 cases:
* No Copy - b=a
* View or Shallow copy - b = a.view()
* Deep copy - b = a.copy()

In [33]:
a = np.array([[ 0,  1,  2,  3],[ 4,  5,  6,  7],[ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [34]:
c = a.view()
c is a

False

In [35]:
c.base is a            # c is a view of the data owned by a

True

In [36]:
c = c.reshape((2, 6))  # a's shape doesn't change
a.shape

(3, 4)

In [37]:
c[0, 4] = 1234         # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [39]:
d = a.copy()  # a new array object with new data is created
d is a

False

In [40]:
d.base is a  # d doesn't share anything with a

False