# Permutation Matrices

***

In [47]:
# Numerical arrays.
import numpy as np

# Permutations.
import itertools as it

## range()

***

https://realpython.com/python-range/

In [48]:
?range

Init signature: range(self, /, *args, **kwargs)
Docstring:     
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).
Type:           type
Subclasses:     

In [49]:
# Generator for integers [0,1,2,3,4,5,6,7,8,9].
range(10)

range(0, 10)

In [50]:
# Looping over the generator.
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [51]:
# Create list from generator.
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
# The reason the last integer (10) is not included.
L = ['a', 'b', 'c', 'd']

list(range(len(L)))

[0, 1, 2, 3]

In [53]:
# Two parameters: start (included) and stop (not included).
list(range(2, 10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
# Including a step.
# Java equivalent: for (i = 2; i < 10; i += 3)
list(range(2, 10, 3))

[2, 5, 8]

## Slicing

***

https://realpython.com/python-strings/#string-slicing


In [55]:
# Example string.
s = "Hello, world!"

# Eighth character, at index 7.
s[7]

'w'

In [56]:
# Print characters at indices 3, 4, and 5.
for i in range(7, 10):
  print(s[i])

w
o
r


In [57]:
# Substring containing those characters.
s[7:10]

'wor'

In [58]:
# [start:stop:step]
s[7:12:2]

'wrd'

In [59]:
# 0 is the default in front of first colon.
s[:9]

'Hello, wo'

In [60]:
# len(s) is the default value after first colon.
s[9:]

'rld!'

In [61]:
# Default step is 1.
s[2:6:]

'llo,'

## Permutations

***

https://docs.python.org/3/library/itertools.html#itertools.permutations


In [62]:
# N
N = 3

# A list of integers up to N.
L = list(range(N))

# Show.
L

[0, 1, 2]

In [63]:
# Generate all permutations of L.
for p in it.permutations(L):
  print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


## Matrices in numpy

***

In [64]:
# N
N = 3

# Entries are [0, 1, 2, ..., N-1] in order.
M = np.arange(N**2)

# Show.
M

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
type(M)

numpy.ndarray

In [66]:
# N
N = 3

# Square matrix with N rows, N columns.
# Entries are [0, 1, 2, ..., N-1] in order.
M = np.arange(N**2).reshape((N,N))

# Show.
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
# First row.
M[0]

array([0, 1, 2])

In [68]:
# Second row, third column.
M[1][2]

5

In [69]:
# Second row, third column.
M[1, 2]

5

In [70]:
# Second row, third column.
M[(1, 2)]

5

In [71]:
# The Matrix Again.
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
# First column.
M[:, 0]

array([0, 3, 6])

In [73]:
# Bottom right four entries.
M[1:, 1:]

array([[4, 5],
       [7, 8]])

In [74]:
# The matrix again.
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
# Permute the rows - note the list!
M[[1,2,0]]

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [76]:
# Permute the columns.
M[:, [1,2,0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

## Generate All Matrices

***

In [77]:
# N
N = 3

# Square matrix with N rows, N columns.
# Entries are [0, 1, 2, ..., N-1] in order.
M = np.arange(N**2).reshape((N,N))

# Show.
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
# Generate all permutations of N indices from 0.
for p in it.permutations(range(N)):
  print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


In [79]:
# Generate all permutations of rows of M.
for p in it.permutations(range(N)):
  print(M[list(p)])
  print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [6 7 8]
 [3 4 5]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]

[[3 4 5]
 [6 7 8]
 [0 1 2]]

[[6 7 8]
 [0 1 2]
 [3 4 5]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]



In [80]:
# Generate all permutations of columns of M.
for p in it.permutations(range(N)):
  print(M[:, list(p)])
  print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 2 1]
 [3 5 4]
 [6 8 7]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]

[[1 2 0]
 [4 5 3]
 [7 8 6]]

[[2 0 1]
 [5 3 4]
 [8 6 7]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]



## The Identity Matrix

***

In [81]:
# N.
N = 3

# The NxN identity matrix.
np.eye(N)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
# The NxN identity matrix with integers.
np.eye(N, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [83]:
# The NxN identity matrix with integers.
I = np.eye(N, dtype=int)

In [84]:
# Generate all possible permutations of rows of I.
for p in it.permutations(range(N)):
  print(I[list(p)])
  print()

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0]
 [0 0 1]
 [0 1 0]]

[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[0 1 0]
 [0 0 1]
 [1 0 0]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]

[[0 0 1]
 [0 1 0]
 [1 0 0]]



In [85]:
# Generate all permutations of columns of I.
for p in it.permutations(range(N)):
  print(I[:, list(p)])
  print()

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0]
 [0 0 1]
 [0 1 0]]

[[0 1 0]
 [1 0 0]
 [0 0 1]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]

[[0 1 0]
 [0 0 1]
 [1 0 0]]

[[0 0 1]
 [0 1 0]
 [1 0 0]]

